/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/office/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["officeLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["officeLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["officeMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDriverLoginNames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["driverLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["driverLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["driverMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCustomers"];
        put?: never;
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/customers/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        get: operations["getCustomer"];
        put: operations["updateCustomer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/customers/{customerId}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        get: operations["listCustomerPrices"];
        put?: never;
        post: operations["setCustomerPrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProducts"];
        put?: never;
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        get: operations["getProduct"];
        put: operations["updateProduct"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrders"];
        put?: never;
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateOrder"];
        trace?: never;
    };
    "/api/office/orders/{orderId}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addOrderLine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/orders/{orderId}/lines/{lineId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
                lineId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteOrderLine"];
        options?: never;
        head?: never;
        patch: operations["updateOrderLine"];
        trace?: never;
    };
    "/api/office/orders/{orderId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/orders/{orderId}/unconfirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unconfirmOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/orders/{orderId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finalizeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDrivers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/routes/{routeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: number;
            };
            cookie?: never;
        };
        get: operations["getRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/routes/{routeId}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/routes/{routeId}/stops/{stopId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: number;
                stopId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeStop"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/routes/{routeId}/sequence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reorderStops"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/routes/{routeId}/out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["routeOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/routes/{routeId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["routeComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/office/stops/{stopId}/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStopProof"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDriverRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver/stops/{stopId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postDriverAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver/routes/{routeId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["driverCompleteRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            fields?: {
                [key: string]: string;
            };
        };
        User: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            realm: "office" | "driver" | "customer";
            displayName: string;
        };
        Driver: {
            /** Format: int64 */
            id: number;
            displayName: string;
        };
        OfficeLogin: {
            email: string;
            password: string;
        };
        DriverLogin: {
            /** Format: int64 */
            userId: number;
            pin: string;
        };
        Customer: {
            /** Format: int64 */
            id: number;
            name: string;
            billingAddress: string;
            deliveryAddress: string;
            contactName: string;
            phone: string;
            email: string;
            deliveryNotes: string;
            deliveryDays: string[];
            qboCustomerId?: string;
            active: boolean;
        };
        CustomerInput: {
            name: string;
            billingAddress?: string;
            deliveryAddress?: string;
            contactName?: string;
            phone?: string;
            email?: string;
            deliveryNotes?: string;
            deliveryDays?: string[];
            qboCustomerId?: string;
            /** @default true */
            active: boolean;
        };
        Product: {
            /** Format: int64 */
            id: number;
            sku: string;
            name: string;
            category: string;
            /** @enum {string} */
            sellUnit: "lb" | "case" | "each";
            catchWeight: boolean;
            /**
             * Format: int64
             * @description hundredths of a pound
             */
            approxCaseWeight?: number;
            /** Format: int64 */
            basePriceCents: number;
            qboItemId?: string;
            active: boolean;
        };
        ProductInput: {
            sku: string;
            name: string;
            category?: string;
            /** @enum {string} */
            sellUnit: "lb" | "case" | "each";
            /** @default false */
            catchWeight: boolean;
            /** Format: int64 */
            approxCaseWeight?: number;
            /** Format: int64 */
            basePriceCents: number;
            qboItemId?: string;
            /** @default true */
            active: boolean;
        };
        CustomerPrice: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            productId: number;
            sku: string;
            productName: string;
            /** Format: int64 */
            priceCents: number;
            effectiveFrom: string;
        };
        PriceInput: {
            /** Format: int64 */
            productId: number;
            /** Format: int64 */
            priceCents: number;
            effectiveFrom: string;
        };
        OrderSummary: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            customerId: number;
            customerName: string;
            requestedDeliveryDate: string;
            status: components["schemas"]["OrderStatus"];
            needsReview: boolean;
            /** Format: int64 */
            lineCount: number;
            notes: string;
        };
        /** @enum {string} */
        OrderStatus: "draft" | "confirmed" | "scheduled" | "delivered" | "finalized" | "cancelled";
        OrderInput: {
            /** Format: int64 */
            customerId: number;
            requestedDeliveryDate: string;
            notes?: string;
        };
        OrderPatch: {
            notes?: string;
            requestedDeliveryDate?: string;
        };
        OrderLine: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            productId: number;
            sku: string;
            productName: string;
            sellUnit: string;
            catchWeight: boolean;
            /**
             * Format: int64
             * @description hundredths of the sell unit
             */
            orderedQty: number;
            /** Format: int64 */
            unitPriceCents: number;
            priceOverridden: boolean;
            /** Format: int64 */
            estWeight?: number;
            /** Format: int64 */
            shippedWeight?: number;
            /** Format: int64 */
            deliveredQty?: number;
            /** Format: int64 */
            deliveredWeight?: number;
            shortageNote: string;
            /** Format: int64 */
            amountCents: number;
            /** @enum {string} */
            amountSource: "delivered" | "shipped" | "estimated" | "ordered";
        };
        LineInput: {
            /** Format: int64 */
            productId: number;
            /** Format: int64 */
            orderedQty: number;
        };
        LinePatch: {
            /** Format: int64 */
            orderedQty?: number;
            /** Format: int64 */
            unitPriceCents?: number;
            /** Format: int64 */
            shippedWeight?: number;
            /** Format: int64 */
            deliveredQty?: number;
            /** Format: int64 */
            deliveredWeight?: number;
            shortageNote?: string;
        };
        Order: {
            /** Format: int64 */
            id: number;
            customer: components["schemas"]["Customer"];
            requestedDeliveryDate: string;
            status: components["schemas"]["OrderStatus"];
            notes: string;
            needsReview: boolean;
            lines: components["schemas"]["OrderLine"][];
            /** Format: int64 */
            totalCents: number;
            /** Format: int64 */
            routeId?: number;
            /** Format: int64 */
            stopId?: number;
            routeStatus?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finalizedAt?: string;
        };
        RouteInput: {
            routeDate: string;
            /** Format: int64 */
            driverUserId: number;
            truckLabel?: string;
        };
        Stop: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            routeId: number;
            /** Format: int64 */
            orderId: number;
            /** Format: int64 */
            sequence: number;
            /** @enum {string} */
            status: "pending" | "delivered" | "skipped";
            /** Format: date-time */
            deliveredAt?: string;
            /** @enum {string} */
            proofType?: "signature" | "photo" | "name";
            /** @description received-by name when proofType is name */
            proofName?: string;
            hasProofImage: boolean;
            skipReason: string;
            driverNote: string;
            customerName: string;
            deliveryAddress: string;
            phone: string;
            contactName: string;
            deliveryNotes: string;
            orderStatus: components["schemas"]["OrderStatus"];
            needsReview: boolean;
            /** Format: int64 */
            lineCount: number;
        };
        Route: {
            /** Format: int64 */
            id: number;
            routeDate: string;
            /** Format: int64 */
            driverUserId: number;
            driverName: string;
            truckLabel: string;
            /** @enum {string} */
            status: "planned" | "out" | "complete";
            /** Format: date-time */
            outAt?: string;
            /** Format: date-time */
            completedAt?: string;
            stops: components["schemas"]["Stop"][];
        };
        AddStopInput: {
            /** Format: int64 */
            orderId: number;
        };
        SequenceInput: {
            stopIds: number[];
        };
        DayView: {
            date: string;
            unscheduled: components["schemas"]["OrderSummary"][];
            routes: components["schemas"]["Route"][];
        };
        DriverStop: {
            stop: components["schemas"]["Stop"];
            order: components["schemas"]["Order"];
        };
        DriverRoute: {
            route: components["schemas"]["Route"];
            stops: components["schemas"]["DriverStop"][];
        };
        Proof: {
            /** @enum {string} */
            type: "signature" | "photo" | "name";
            /** @description PNG or JPEG bytes */
            dataBase64?: string;
            name?: string;
        };
        LineAdjustment: {
            /** Format: int64 */
            lineId: number;
            /** Format: int64 */
            deliveredQty?: number;
            /** Format: int64 */
            deliveredWeight?: number;
            shortageNote?: string;
        };
        DriverAction: {
            /** @description client-generated UUID; replays are acknowledged and not reapplied */
            clientId: string;
            /** @enum {string} */
            type: "deliver" | "adjust" | "skip";
            proof?: components["schemas"]["Proof"];
            lines?: components["schemas"]["LineAdjustment"][];
            note?: string;
            skipReason?: string;
        };
        DriverActionResult: {
            applied: boolean;
            stop: components["schemas"]["DriverStop"];
        };
    };
    responses: {
        /** @description error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    officeLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfficeLogin"];
            };
        };
        responses: {
            /** @description logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    officeLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    officeMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDriverLoginNames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description active drivers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Driver"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    driverLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverLogin"];
            };
        };
        responses: {
            /** @description logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    driverLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    driverMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listCustomers: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description customers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listCustomerPrices: {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD, defaults to today */
                asOf?: string;
            };
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current prices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPrice"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    setCustomerPrice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPrice"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                date?: string;
                status?: string;
                customerId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderPatch"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addOrderLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineInput"];
            };
        };
        responses: {
            /** @description order with new line */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteOrderLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
                lineId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateOrderLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
                lineId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinePatch"];
            };
        };
        responses: {
            /** @description order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    confirmOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    unconfirmOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    finalizeOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDay: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description day view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayView"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDrivers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description drivers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Driver"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRoute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteInput"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddStopInput"];
            };
        };
        responses: {
            /** @description route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    removeStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: number;
                stopId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reorderStops: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SequenceInput"];
            };
        };
        responses: {
            /** @description route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    routeOut: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    routeComplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getStopProof: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stopId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description proof image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/jpeg": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDriverRoute: {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD, defaults to today */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description today's route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverRoute"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    postDriverAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stopId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverAction"];
            };
        };
        responses: {
            /** @description result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverActionResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    driverCompleteRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description route */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverRoute"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
