// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, billing_address, delivery_address, contact_name, phone, email,
  delivery_notes, delivery_days, qbo_customer_id, active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, TRUE, ?, ?) RETURNING id, name, billing_address, delivery_address, contact_name, phone, email, delivery_notes, delivery_days, qbo_customer_id, active, created_at, updated_at
`

type CreateCustomerParams struct {
	Name            string
	BillingAddress  string
	DeliveryAddress string
	ContactName     string
	Phone           string
	Email           string
	DeliveryNotes   string
	DeliveryDays    string
	QboCustomerID   sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.Name,
		arg.BillingAddress,
		arg.DeliveryAddress,
		arg.ContactName,
		arg.Phone,
		arg.Email,
		arg.DeliveryNotes,
		arg.DeliveryDays,
		arg.QboCustomerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingAddress,
		&i.DeliveryAddress,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.DeliveryNotes,
		&i.DeliveryDays,
		&i.QboCustomerID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, billing_address, delivery_address, contact_name, phone, email, delivery_notes, delivery_days, qbo_customer_id, active, created_at, updated_at FROM customers WHERE id = ?
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingAddress,
		&i.DeliveryAddress,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.DeliveryNotes,
		&i.DeliveryDays,
		&i.QboCustomerID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByName = `-- name: GetCustomerByName :one
SELECT id, name, billing_address, delivery_address, contact_name, phone, email, delivery_notes, delivery_days, qbo_customer_id, active, created_at, updated_at FROM customers WHERE name = ?
`

func (q *Queries) GetCustomerByName(ctx context.Context, name string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByName, name)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingAddress,
		&i.DeliveryAddress,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.DeliveryNotes,
		&i.DeliveryDays,
		&i.QboCustomerID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByQBO = `-- name: GetCustomerByQBO :one
SELECT id, name, billing_address, delivery_address, contact_name, phone, email, delivery_notes, delivery_days, qbo_customer_id, active, created_at, updated_at FROM customers WHERE qbo_customer_id = ?
`

func (q *Queries) GetCustomerByQBO(ctx context.Context, qboCustomerID sql.NullString) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByQBO, qboCustomerID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingAddress,
		&i.DeliveryAddress,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.DeliveryNotes,
		&i.DeliveryDays,
		&i.QboCustomerID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, billing_address, delivery_address, contact_name, phone, email, delivery_notes, delivery_days, qbo_customer_id, active, created_at, updated_at FROM customers WHERE (?1 = TRUE OR active = TRUE) ORDER BY name
`

func (q *Queries) ListCustomers(ctx context.Context, includeInactive interface{}) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers, includeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BillingAddress,
			&i.DeliveryAddress,
			&i.ContactName,
			&i.Phone,
			&i.Email,
			&i.DeliveryNotes,
			&i.DeliveryDays,
			&i.QboCustomerID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers SET name = ?, billing_address = ?, delivery_address = ?, contact_name = ?,
  phone = ?, email = ?, delivery_notes = ?, delivery_days = ?, qbo_customer_id = ?, active = ?, updated_at = ?
WHERE id = ? RETURNING id, name, billing_address, delivery_address, contact_name, phone, email, delivery_notes, delivery_days, qbo_customer_id, active, created_at, updated_at
`

type UpdateCustomerParams struct {
	Name            string
	BillingAddress  string
	DeliveryAddress string
	ContactName     string
	Phone           string
	Email           string
	DeliveryNotes   string
	DeliveryDays    string
	QboCustomerID   sql.NullString
	Active          bool
	UpdatedAt       time.Time
	ID              int64
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, updateCustomer,
		arg.Name,
		arg.BillingAddress,
		arg.DeliveryAddress,
		arg.ContactName,
		arg.Phone,
		arg.Email,
		arg.DeliveryNotes,
		arg.DeliveryDays,
		arg.QboCustomerID,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BillingAddress,
		&i.DeliveryAddress,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.DeliveryNotes,
		&i.DeliveryDays,
		&i.QboCustomerID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
