// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID              int64
	Name            string
	BillingAddress  string
	DeliveryAddress string
	ContactName     string
	Phone           string
	Email           string
	DeliveryNotes   string
	DeliveryDays    string
	QboCustomerID   sql.NullString
	Active          bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type CustomerPrice struct {
	ID            int64
	CustomerID    int64
	ProductID     int64
	PriceCents    int64
	EffectiveFrom string
	CreatedAt     time.Time
}

type DeliveryRoute struct {
	ID           int64
	RouteDate    string
	DriverUserID int64
	TruckLabel   string
	Status       string
	CreatedAt    time.Time
	OutAt        sql.NullTime
	CompletedAt  sql.NullTime
}

type DeliveryStop struct {
	ID          int64
	RouteID     int64
	OrderID     int64
	Sequence    int64
	Status      string
	DeliveredAt sql.NullTime
	ProofType   sql.NullString
	ProofRef    sql.NullString
	SkipReason  string
	DriverNote  string
}

type DriverAction struct {
	ClientID   string
	StopID     int64
	ActionType string
	Payload    string
	ReceivedAt time.Time
}

type Order struct {
	ID                    int64
	CustomerID            int64
	RequestedDeliveryDate string
	Status                string
	Notes                 string
	CreatedBy             sql.NullInt64
	NeedsReview           bool
	CreatedAt             time.Time
	UpdatedAt             time.Time
	FinalizedAt           sql.NullTime
}

type OrderLine struct {
	ID              int64
	OrderID         int64
	ProductID       int64
	OrderedQty      int64
	UnitPriceCents  int64
	PriceOverridden bool
	EstWeight       sql.NullInt64
	ShippedWeight   sql.NullInt64
	DeliveredQty    sql.NullInt64
	DeliveredWeight sql.NullInt64
	ShortageNote    string
}

type Product struct {
	ID               int64
	Sku              string
	Name             string
	Category         string
	SellUnit         string
	CatchWeight      bool
	ApproxCaseWeight sql.NullInt64
	BasePriceCents   int64
	QboItemID        sql.NullString
	Active           bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Session struct {
	ID        string
	UserID    int64
	Realm     string
	ExpiresAt time.Time
}

type User struct {
	ID           int64
	Realm        string
	DisplayName  string
	Email        sql.NullString
	PasswordHash sql.NullString
	PinHash      sql.NullString
	CustomerID   sql.NullInt64
	Active       bool
	CreatedAt    time.Time
}
