// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countOrderLines = `-- name: CountOrderLines :one
SELECT count(*) FROM order_lines WHERE order_id = ?
`

func (q *Queries) CountOrderLines(ctx context.Context, orderID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrderLines, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id, requested_delivery_date, status, notes, created_by, needs_review, created_at, updated_at)
VALUES (?, ?, 'draft', ?, ?, FALSE, ?, ?) RETURNING id, customer_id, requested_delivery_date, status, notes, created_by, needs_review, created_at, updated_at, finalized_at
`

type CreateOrderParams struct {
	CustomerID            int64
	RequestedDeliveryDate string
	Notes                 string
	CreatedBy             sql.NullInt64
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.CustomerID,
		arg.RequestedDeliveryDate,
		arg.Notes,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RequestedDeliveryDate,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.NeedsReview,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const createOrderLine = `-- name: CreateOrderLine :one
INSERT INTO order_lines (order_id, product_id, ordered_qty, unit_price_cents, price_overridden, est_weight)
VALUES (?, ?, ?, ?, FALSE, ?) RETURNING id, order_id, product_id, ordered_qty, unit_price_cents, price_overridden, est_weight, shipped_weight, delivered_qty, delivered_weight, shortage_note
`

type CreateOrderLineParams struct {
	OrderID        int64
	ProductID      int64
	OrderedQty     int64
	UnitPriceCents int64
	EstWeight      sql.NullInt64
}

func (q *Queries) CreateOrderLine(ctx context.Context, arg CreateOrderLineParams) (OrderLine, error) {
	row := q.db.QueryRowContext(ctx, createOrderLine,
		arg.OrderID,
		arg.ProductID,
		arg.OrderedQty,
		arg.UnitPriceCents,
		arg.EstWeight,
	)
	var i OrderLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.OrderedQty,
		&i.UnitPriceCents,
		&i.PriceOverridden,
		&i.EstWeight,
		&i.ShippedWeight,
		&i.DeliveredQty,
		&i.DeliveredWeight,
		&i.ShortageNote,
	)
	return i, err
}

const deleteOrderLine = `-- name: DeleteOrderLine :exec
DELETE FROM order_lines WHERE id = ? AND order_id = ?
`

type DeleteOrderLineParams struct {
	ID      int64
	OrderID int64
}

func (q *Queries) DeleteOrderLine(ctx context.Context, arg DeleteOrderLineParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrderLine, arg.ID, arg.OrderID)
	return err
}

const deleteStop = `-- name: DeleteStop :exec
DELETE FROM delivery_stops WHERE id = ?
`

func (q *Queries) DeleteStop(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStop, id)
	return err
}

const finalizeOrder = `-- name: FinalizeOrder :exec
UPDATE orders SET status = 'finalized', needs_review = FALSE, finalized_at = ?, updated_at = ? WHERE id = ?
`

type FinalizeOrderParams struct {
	FinalizedAt sql.NullTime
	UpdatedAt   time.Time
	ID          int64
}

func (q *Queries) FinalizeOrder(ctx context.Context, arg FinalizeOrderParams) error {
	_, err := q.db.ExecContext(ctx, finalizeOrder, arg.FinalizedAt, arg.UpdatedAt, arg.ID)
	return err
}

const getActiveStopForOrder = `-- name: GetActiveStopForOrder :one
SELECT s.id AS stop_id, s.route_id, s.status AS stop_status, r.status AS route_status, r.route_date, r.driver_user_id
FROM delivery_stops s JOIN delivery_routes r ON r.id = s.route_id
WHERE s.order_id = ? AND s.status <> 'skipped'
`

type GetActiveStopForOrderRow struct {
	StopID       int64
	RouteID      int64
	StopStatus   string
	RouteStatus  string
	RouteDate    string
	DriverUserID int64
}

func (q *Queries) GetActiveStopForOrder(ctx context.Context, orderID int64) (GetActiveStopForOrderRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveStopForOrder, orderID)
	var i GetActiveStopForOrderRow
	err := row.Scan(
		&i.StopID,
		&i.RouteID,
		&i.StopStatus,
		&i.RouteStatus,
		&i.RouteDate,
		&i.DriverUserID,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, customer_id, requested_delivery_date, status, notes, created_by, needs_review, created_at, updated_at, finalized_at FROM orders WHERE id = ?
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RequestedDeliveryDate,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.NeedsReview,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getOrderLine = `-- name: GetOrderLine :one
SELECT id, order_id, product_id, ordered_qty, unit_price_cents, price_overridden, est_weight, shipped_weight, delivered_qty, delivered_weight, shortage_note FROM order_lines WHERE id = ? AND order_id = ?
`

type GetOrderLineParams struct {
	ID      int64
	OrderID int64
}

func (q *Queries) GetOrderLine(ctx context.Context, arg GetOrderLineParams) (OrderLine, error) {
	row := q.db.QueryRowContext(ctx, getOrderLine, arg.ID, arg.OrderID)
	var i OrderLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.OrderedQty,
		&i.UnitPriceCents,
		&i.PriceOverridden,
		&i.EstWeight,
		&i.ShippedWeight,
		&i.DeliveredQty,
		&i.DeliveredWeight,
		&i.ShortageNote,
	)
	return i, err
}

const listOrderLines = `-- name: ListOrderLines :many
SELECT ol.id, ol.order_id, ol.product_id, ol.ordered_qty, ol.unit_price_cents, ol.price_overridden, ol.est_weight, ol.shipped_weight, ol.delivered_qty, ol.delivered_weight, ol.shortage_note, p.sku, p.name AS product_name, p.category, p.sell_unit, p.catch_weight, p.approx_case_weight, p.base_price_cents
FROM order_lines ol JOIN products p ON p.id = ol.product_id
WHERE ol.order_id = ? ORDER BY ol.id
`

type ListOrderLinesRow struct {
	ID               int64
	OrderID          int64
	ProductID        int64
	OrderedQty       int64
	UnitPriceCents   int64
	PriceOverridden  bool
	EstWeight        sql.NullInt64
	ShippedWeight    sql.NullInt64
	DeliveredQty     sql.NullInt64
	DeliveredWeight  sql.NullInt64
	ShortageNote     string
	Sku              string
	ProductName      string
	Category         string
	SellUnit         string
	CatchWeight      bool
	ApproxCaseWeight sql.NullInt64
	BasePriceCents   int64
}

func (q *Queries) ListOrderLines(ctx context.Context, orderID int64) ([]ListOrderLinesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrderLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderLinesRow
	for rows.Next() {
		var i ListOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.OrderedQty,
			&i.UnitPriceCents,
			&i.PriceOverridden,
			&i.EstWeight,
			&i.ShippedWeight,
			&i.DeliveredQty,
			&i.DeliveredWeight,
			&i.ShortageNote,
			&i.Sku,
			&i.ProductName,
			&i.Category,
			&i.SellUnit,
			&i.CatchWeight,
			&i.ApproxCaseWeight,
			&i.BasePriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT o.id, o.customer_id, o.requested_delivery_date, o.status, o.notes, o.created_by, o.needs_review, o.created_at, o.updated_at, o.finalized_at, c.name AS customer_name,
  CAST((SELECT count(*) FROM order_lines ol WHERE ol.order_id = o.id) AS INTEGER) AS line_count
FROM orders o JOIN customers c ON c.id = o.customer_id
WHERE (CAST(?1 AS TEXT) = '' OR o.requested_delivery_date = ?1)
  AND (CAST(?2 AS TEXT) = '' OR o.status = ?2)
  AND (CAST(?3 AS INTEGER) = 0 OR o.customer_id = ?3)
ORDER BY o.requested_delivery_date DESC, o.id DESC
LIMIT 500
`

type ListOrdersParams struct {
	Date       string
	Status     string
	CustomerID int64
}

type ListOrdersRow struct {
	ID                    int64
	CustomerID            int64
	RequestedDeliveryDate string
	Status                string
	Notes                 string
	CreatedBy             sql.NullInt64
	NeedsReview           bool
	CreatedAt             time.Time
	UpdatedAt             time.Time
	FinalizedAt           sql.NullTime
	CustomerName          string
	LineCount             int64
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrders, arg.Date, arg.Status, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.RequestedDeliveryDate,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.NeedsReview,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinalizedAt,
			&i.CustomerName,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnscheduledOrdersForDate = `-- name: ListUnscheduledOrdersForDate :many
SELECT o.id, o.customer_id, o.requested_delivery_date, o.status, o.notes, o.created_by, o.needs_review, o.created_at, o.updated_at, o.finalized_at, c.name AS customer_name,
  CAST((SELECT count(*) FROM order_lines ol WHERE ol.order_id = o.id) AS INTEGER) AS line_count
FROM orders o JOIN customers c ON c.id = o.customer_id
WHERE o.requested_delivery_date = ? AND o.status = 'confirmed'
ORDER BY c.name
`

type ListUnscheduledOrdersForDateRow struct {
	ID                    int64
	CustomerID            int64
	RequestedDeliveryDate string
	Status                string
	Notes                 string
	CreatedBy             sql.NullInt64
	NeedsReview           bool
	CreatedAt             time.Time
	UpdatedAt             time.Time
	FinalizedAt           sql.NullTime
	CustomerName          string
	LineCount             int64
}

func (q *Queries) ListUnscheduledOrdersForDate(ctx context.Context, requestedDeliveryDate string) ([]ListUnscheduledOrdersForDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnscheduledOrdersForDate, requestedDeliveryDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnscheduledOrdersForDateRow
	for rows.Next() {
		var i ListUnscheduledOrdersForDateRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.RequestedDeliveryDate,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.NeedsReview,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinalizedAt,
			&i.CustomerName,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetDeliveredForOrder = `-- name: ResetDeliveredForOrder :exec
UPDATE order_lines SET delivered_qty = NULL, delivered_weight = NULL, shortage_note = '' WHERE order_id = ?
`

func (q *Queries) ResetDeliveredForOrder(ctx context.Context, orderID int64) error {
	_, err := q.db.ExecContext(ctx, resetDeliveredForOrder, orderID)
	return err
}

const setOrderNeedsReview = `-- name: SetOrderNeedsReview :exec
UPDATE orders SET needs_review = ?, updated_at = ? WHERE id = ?
`

type SetOrderNeedsReviewParams struct {
	NeedsReview bool
	UpdatedAt   time.Time
	ID          int64
}

func (q *Queries) SetOrderNeedsReview(ctx context.Context, arg SetOrderNeedsReviewParams) error {
	_, err := q.db.ExecContext(ctx, setOrderNeedsReview, arg.NeedsReview, arg.UpdatedAt, arg.ID)
	return err
}

const updateOrderLine = `-- name: UpdateOrderLine :exec
UPDATE order_lines SET ordered_qty = ?, unit_price_cents = ?, price_overridden = ?, est_weight = ?,
  shipped_weight = ?, delivered_qty = ?, delivered_weight = ?, shortage_note = ?
WHERE id = ?
`

type UpdateOrderLineParams struct {
	OrderedQty      int64
	UnitPriceCents  int64
	PriceOverridden bool
	EstWeight       sql.NullInt64
	ShippedWeight   sql.NullInt64
	DeliveredQty    sql.NullInt64
	DeliveredWeight sql.NullInt64
	ShortageNote    string
	ID              int64
}

func (q *Queries) UpdateOrderLine(ctx context.Context, arg UpdateOrderLineParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderLine,
		arg.OrderedQty,
		arg.UnitPriceCents,
		arg.PriceOverridden,
		arg.EstWeight,
		arg.ShippedWeight,
		arg.DeliveredQty,
		arg.DeliveredWeight,
		arg.ShortageNote,
		arg.ID,
	)
	return err
}

const updateOrderMeta = `-- name: UpdateOrderMeta :exec
UPDATE orders SET notes = ?, requested_delivery_date = ?, updated_at = ? WHERE id = ?
`

type UpdateOrderMetaParams struct {
	Notes                 string
	RequestedDeliveryDate string
	UpdatedAt             time.Time
	ID                    int64
}

func (q *Queries) UpdateOrderMeta(ctx context.Context, arg UpdateOrderMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderMeta,
		arg.Notes,
		arg.RequestedDeliveryDate,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
