// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prices.sql

package queries

import (
	"context"
	"time"
)

const createCustomerPrice = `-- name: CreateCustomerPrice :one
INSERT INTO customer_prices (customer_id, product_id, price_cents, effective_from, created_at)
VALUES (?, ?, ?, ?, ?) RETURNING id, customer_id, product_id, price_cents, effective_from, created_at
`

type CreateCustomerPriceParams struct {
	CustomerID    int64
	ProductID     int64
	PriceCents    int64
	EffectiveFrom string
	CreatedAt     time.Time
}

func (q *Queries) CreateCustomerPrice(ctx context.Context, arg CreateCustomerPriceParams) (CustomerPrice, error) {
	row := q.db.QueryRowContext(ctx, createCustomerPrice,
		arg.CustomerID,
		arg.ProductID,
		arg.PriceCents,
		arg.EffectiveFrom,
		arg.CreatedAt,
	)
	var i CustomerPrice
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProductID,
		&i.PriceCents,
		&i.EffectiveFrom,
		&i.CreatedAt,
	)
	return i, err
}

const listCurrentCustomerPrices = `-- name: ListCurrentCustomerPrices :many
SELECT cp.id, cp.customer_id, cp.product_id, cp.price_cents, cp.effective_from, cp.created_at, p.sku, p.name AS product_name
FROM customer_prices cp
JOIN products p ON p.id = cp.product_id
WHERE cp.customer_id = ?
  AND cp.id = (
    SELECT c2.id FROM customer_prices c2
    WHERE c2.customer_id = cp.customer_id AND c2.product_id = cp.product_id AND c2.effective_from <= ?2
    ORDER BY c2.effective_from DESC, c2.id DESC LIMIT 1)
ORDER BY p.name
`

type ListCurrentCustomerPricesParams struct {
	CustomerID int64
	AsOf       string
}

type ListCurrentCustomerPricesRow struct {
	ID            int64
	CustomerID    int64
	ProductID     int64
	PriceCents    int64
	EffectiveFrom string
	CreatedAt     time.Time
	Sku           string
	ProductName   string
}

func (q *Queries) ListCurrentCustomerPrices(ctx context.Context, arg ListCurrentCustomerPricesParams) ([]ListCurrentCustomerPricesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentCustomerPrices, arg.CustomerID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentCustomerPricesRow
	for rows.Next() {
		var i ListCurrentCustomerPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProductID,
			&i.PriceCents,
			&i.EffectiveFrom,
			&i.CreatedAt,
			&i.Sku,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerPriceRows = `-- name: ListCustomerPriceRows :many
SELECT id, customer_id, product_id, price_cents, effective_from, created_at FROM customer_prices WHERE customer_id = ? AND product_id = ? ORDER BY effective_from DESC, id DESC
`

type ListCustomerPriceRowsParams struct {
	CustomerID int64
	ProductID  int64
}

func (q *Queries) ListCustomerPriceRows(ctx context.Context, arg ListCustomerPriceRowsParams) ([]CustomerPrice, error) {
	rows, err := q.db.QueryContext(ctx, listCustomerPriceRows, arg.CustomerID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerPrice
	for rows.Next() {
		var i CustomerPrice
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProductID,
			&i.PriceCents,
			&i.EffectiveFrom,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
