// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (sku, name, category, sell_unit, catch_weight, approx_case_weight,
  base_price_cents, qbo_item_id, active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, TRUE, ?, ?) RETURNING id, sku, name, category, sell_unit, catch_weight, approx_case_weight, base_price_cents, qbo_item_id, active, created_at, updated_at
`

type CreateProductParams struct {
	Sku              string
	Name             string
	Category         string
	SellUnit         string
	CatchWeight      bool
	ApproxCaseWeight sql.NullInt64
	BasePriceCents   int64
	QboItemID        sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Category,
		arg.SellUnit,
		arg.CatchWeight,
		arg.ApproxCaseWeight,
		arg.BasePriceCents,
		arg.QboItemID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.SellUnit,
		&i.CatchWeight,
		&i.ApproxCaseWeight,
		&i.BasePriceCents,
		&i.QboItemID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, sku, name, category, sell_unit, catch_weight, approx_case_weight, base_price_cents, qbo_item_id, active, created_at, updated_at FROM products WHERE id = ?
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.SellUnit,
		&i.CatchWeight,
		&i.ApproxCaseWeight,
		&i.BasePriceCents,
		&i.QboItemID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, sku, name, category, sell_unit, catch_weight, approx_case_weight, base_price_cents, qbo_item_id, active, created_at, updated_at FROM products WHERE sku = ?
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.SellUnit,
		&i.CatchWeight,
		&i.ApproxCaseWeight,
		&i.BasePriceCents,
		&i.QboItemID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, sku, name, category, sell_unit, catch_weight, approx_case_weight, base_price_cents, qbo_item_id, active, created_at, updated_at FROM products WHERE (CAST(?1 AS BOOLEAN) = TRUE OR active = TRUE) ORDER BY category, name
`

func (q *Queries) ListProducts(ctx context.Context, includeInactive bool) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, includeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Category,
			&i.SellUnit,
			&i.CatchWeight,
			&i.ApproxCaseWeight,
			&i.BasePriceCents,
			&i.QboItemID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET sku = ?, name = ?, category = ?, sell_unit = ?, catch_weight = ?,
  approx_case_weight = ?, base_price_cents = ?, qbo_item_id = ?, active = ?, updated_at = ?
WHERE id = ? RETURNING id, sku, name, category, sell_unit, catch_weight, approx_case_weight, base_price_cents, qbo_item_id, active, created_at, updated_at
`

type UpdateProductParams struct {
	Sku              string
	Name             string
	Category         string
	SellUnit         string
	CatchWeight      bool
	ApproxCaseWeight sql.NullInt64
	BasePriceCents   int64
	QboItemID        sql.NullString
	Active           bool
	UpdatedAt        time.Time
	ID               int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Sku,
		arg.Name,
		arg.Category,
		arg.SellUnit,
		arg.CatchWeight,
		arg.ApproxCaseWeight,
		arg.BasePriceCents,
		arg.QboItemID,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.SellUnit,
		&i.CatchWeight,
		&i.ApproxCaseWeight,
		&i.BasePriceCents,
		&i.QboItemID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
