// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countPendingStops = `-- name: CountPendingStops :one
SELECT count(*) FROM delivery_stops WHERE route_id = ? AND status = 'pending'
`

func (q *Queries) CountPendingStops(ctx context.Context, routeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingStops, routeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDriverAction = `-- name: CreateDriverAction :exec
INSERT INTO driver_actions (client_id, stop_id, action_type, payload, received_at) VALUES (?, ?, ?, ?, ?)
`

type CreateDriverActionParams struct {
	ClientID   string
	StopID     int64
	ActionType string
	Payload    string
	ReceivedAt time.Time
}

func (q *Queries) CreateDriverAction(ctx context.Context, arg CreateDriverActionParams) error {
	_, err := q.db.ExecContext(ctx, createDriverAction,
		arg.ClientID,
		arg.StopID,
		arg.ActionType,
		arg.Payload,
		arg.ReceivedAt,
	)
	return err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO delivery_routes (route_date, driver_user_id, truck_label, status, created_at)
VALUES (?, ?, ?, 'planned', ?) RETURNING id, route_date, driver_user_id, truck_label, status, created_at, out_at, completed_at
`

type CreateRouteParams struct {
	RouteDate    string
	DriverUserID int64
	TruckLabel   string
	CreatedAt    time.Time
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (DeliveryRoute, error) {
	row := q.db.QueryRowContext(ctx, createRoute,
		arg.RouteDate,
		arg.DriverUserID,
		arg.TruckLabel,
		arg.CreatedAt,
	)
	var i DeliveryRoute
	err := row.Scan(
		&i.ID,
		&i.RouteDate,
		&i.DriverUserID,
		&i.TruckLabel,
		&i.Status,
		&i.CreatedAt,
		&i.OutAt,
		&i.CompletedAt,
	)
	return i, err
}

const createStop = `-- name: CreateStop :one
INSERT INTO delivery_stops (route_id, order_id, sequence, status) VALUES (?, ?, ?, 'pending') RETURNING id, route_id, order_id, sequence, status, delivered_at, proof_type, proof_ref, skip_reason, driver_note
`

type CreateStopParams struct {
	RouteID  int64
	OrderID  int64
	Sequence int64
}

func (q *Queries) CreateStop(ctx context.Context, arg CreateStopParams) (DeliveryStop, error) {
	row := q.db.QueryRowContext(ctx, createStop, arg.RouteID, arg.OrderID, arg.Sequence)
	var i DeliveryStop
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.OrderID,
		&i.Sequence,
		&i.Status,
		&i.DeliveredAt,
		&i.ProofType,
		&i.ProofRef,
		&i.SkipReason,
		&i.DriverNote,
	)
	return i, err
}

const getDriverAction = `-- name: GetDriverAction :one
SELECT client_id, stop_id, action_type, payload, received_at FROM driver_actions WHERE client_id = ?
`

func (q *Queries) GetDriverAction(ctx context.Context, clientID string) (DriverAction, error) {
	row := q.db.QueryRowContext(ctx, getDriverAction, clientID)
	var i DriverAction
	err := row.Scan(
		&i.ClientID,
		&i.StopID,
		&i.ActionType,
		&i.Payload,
		&i.ReceivedAt,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT id, route_date, driver_user_id, truck_label, status, created_at, out_at, completed_at FROM delivery_routes WHERE id = ?
`

func (q *Queries) GetRoute(ctx context.Context, id int64) (DeliveryRoute, error) {
	row := q.db.QueryRowContext(ctx, getRoute, id)
	var i DeliveryRoute
	err := row.Scan(
		&i.ID,
		&i.RouteDate,
		&i.DriverUserID,
		&i.TruckLabel,
		&i.Status,
		&i.CreatedAt,
		&i.OutAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRouteForDriverDate = `-- name: GetRouteForDriverDate :one
SELECT id, route_date, driver_user_id, truck_label, status, created_at, out_at, completed_at FROM delivery_routes WHERE driver_user_id = ? AND route_date = ? AND status <> 'complete' ORDER BY id LIMIT 1
`

type GetRouteForDriverDateParams struct {
	DriverUserID int64
	RouteDate    string
}

func (q *Queries) GetRouteForDriverDate(ctx context.Context, arg GetRouteForDriverDateParams) (DeliveryRoute, error) {
	row := q.db.QueryRowContext(ctx, getRouteForDriverDate, arg.DriverUserID, arg.RouteDate)
	var i DeliveryRoute
	err := row.Scan(
		&i.ID,
		&i.RouteDate,
		&i.DriverUserID,
		&i.TruckLabel,
		&i.Status,
		&i.CreatedAt,
		&i.OutAt,
		&i.CompletedAt,
	)
	return i, err
}

const getStop = `-- name: GetStop :one
SELECT id, route_id, order_id, sequence, status, delivered_at, proof_type, proof_ref, skip_reason, driver_note FROM delivery_stops WHERE id = ?
`

func (q *Queries) GetStop(ctx context.Context, id int64) (DeliveryStop, error) {
	row := q.db.QueryRowContext(ctx, getStop, id)
	var i DeliveryStop
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.OrderID,
		&i.Sequence,
		&i.Status,
		&i.DeliveredAt,
		&i.ProofType,
		&i.ProofRef,
		&i.SkipReason,
		&i.DriverNote,
	)
	return i, err
}

const listRoutesByDate = `-- name: ListRoutesByDate :many
SELECT id, route_date, driver_user_id, truck_label, status, created_at, out_at, completed_at FROM delivery_routes WHERE route_date = ? ORDER BY id
`

func (q *Queries) ListRoutesByDate(ctx context.Context, routeDate string) ([]DeliveryRoute, error) {
	rows, err := q.db.QueryContext(ctx, listRoutesByDate, routeDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryRoute
	for rows.Next() {
		var i DeliveryRoute
		if err := rows.Scan(
			&i.ID,
			&i.RouteDate,
			&i.DriverUserID,
			&i.TruckLabel,
			&i.Status,
			&i.CreatedAt,
			&i.OutAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStopsForRoute = `-- name: ListStopsForRoute :many
SELECT s.id, s.route_id, s.order_id, s.sequence, s.status, s.delivered_at, s.proof_type, s.proof_ref, s.skip_reason, s.driver_note, o.customer_id, o.status AS order_status, o.needs_review, o.requested_delivery_date, o.notes AS order_notes,
  c.name AS customer_name, c.delivery_address, c.phone, c.contact_name, c.delivery_notes,
  CAST((SELECT count(*) FROM order_lines ol WHERE ol.order_id = o.id) AS INTEGER) AS line_count
FROM delivery_stops s
JOIN orders o ON o.id = s.order_id
JOIN customers c ON c.id = o.customer_id
WHERE s.route_id = ? ORDER BY s.sequence, s.id
`

type ListStopsForRouteRow struct {
	ID                    int64
	RouteID               int64
	OrderID               int64
	Sequence              int64
	Status                string
	DeliveredAt           sql.NullTime
	ProofType             sql.NullString
	ProofRef              sql.NullString
	SkipReason            string
	DriverNote            string
	CustomerID            int64
	OrderStatus           string
	NeedsReview           bool
	RequestedDeliveryDate string
	OrderNotes            string
	CustomerName          string
	DeliveryAddress       string
	Phone                 string
	ContactName           string
	DeliveryNotes         string
	LineCount             int64
}

func (q *Queries) ListStopsForRoute(ctx context.Context, routeID int64) ([]ListStopsForRouteRow, error) {
	rows, err := q.db.QueryContext(ctx, listStopsForRoute, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStopsForRouteRow
	for rows.Next() {
		var i ListStopsForRouteRow
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.OrderID,
			&i.Sequence,
			&i.Status,
			&i.DeliveredAt,
			&i.ProofType,
			&i.ProofRef,
			&i.SkipReason,
			&i.DriverNote,
			&i.CustomerID,
			&i.OrderStatus,
			&i.NeedsReview,
			&i.RequestedDeliveryDate,
			&i.OrderNotes,
			&i.CustomerName,
			&i.DeliveryAddress,
			&i.Phone,
			&i.ContactName,
			&i.DeliveryNotes,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxStopSequence = `-- name: MaxStopSequence :one
SELECT CAST(coalesce(max(sequence), 0) AS INTEGER) FROM delivery_stops WHERE route_id = ?
`

func (q *Queries) MaxStopSequence(ctx context.Context, routeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxStopSequence, routeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateRouteStatus = `-- name: UpdateRouteStatus :exec
UPDATE delivery_routes SET status = ?, out_at = ?, completed_at = ? WHERE id = ?
`

type UpdateRouteStatusParams struct {
	Status      string
	OutAt       sql.NullTime
	CompletedAt sql.NullTime
	ID          int64
}

func (q *Queries) UpdateRouteStatus(ctx context.Context, arg UpdateRouteStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRouteStatus,
		arg.Status,
		arg.OutAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}

const updateStopDelivered = `-- name: UpdateStopDelivered :exec
UPDATE delivery_stops SET status = 'delivered', delivered_at = ?, proof_type = ?, proof_ref = ?, driver_note = ? WHERE id = ?
`

type UpdateStopDeliveredParams struct {
	DeliveredAt sql.NullTime
	ProofType   sql.NullString
	ProofRef    sql.NullString
	DriverNote  string
	ID          int64
}

func (q *Queries) UpdateStopDelivered(ctx context.Context, arg UpdateStopDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, updateStopDelivered,
		arg.DeliveredAt,
		arg.ProofType,
		arg.ProofRef,
		arg.DriverNote,
		arg.ID,
	)
	return err
}

const updateStopNote = `-- name: UpdateStopNote :exec
UPDATE delivery_stops SET driver_note = ? WHERE id = ?
`

type UpdateStopNoteParams struct {
	DriverNote string
	ID         int64
}

func (q *Queries) UpdateStopNote(ctx context.Context, arg UpdateStopNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateStopNote, arg.DriverNote, arg.ID)
	return err
}

const updateStopSequence = `-- name: UpdateStopSequence :exec
UPDATE delivery_stops SET sequence = ? WHERE id = ? AND route_id = ?
`

type UpdateStopSequenceParams struct {
	Sequence int64
	ID       int64
	RouteID  int64
}

func (q *Queries) UpdateStopSequence(ctx context.Context, arg UpdateStopSequenceParams) error {
	_, err := q.db.ExecContext(ctx, updateStopSequence, arg.Sequence, arg.ID, arg.RouteID)
	return err
}

const updateStopSkipped = `-- name: UpdateStopSkipped :exec
UPDATE delivery_stops SET status = 'skipped', skip_reason = ?, driver_note = ? WHERE id = ?
`

type UpdateStopSkippedParams struct {
	SkipReason string
	DriverNote string
	ID         int64
}

func (q *Queries) UpdateStopSkipped(ctx context.Context, arg UpdateStopSkippedParams) error {
	_, err := q.db.ExecContext(ctx, updateStopSkipped, arg.SkipReason, arg.DriverNote, arg.ID)
	return err
}
