// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, realm, expires_at) VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	UserID    int64
	Realm     string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Realm,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (realm, display_name, email, password_hash, pin_hash, customer_id, active, created_at)
VALUES (?, ?, ?, ?, ?, ?, TRUE, ?) RETURNING id, realm, display_name, email, password_hash, pin_hash, customer_id, active, created_at
`

type CreateUserParams struct {
	Realm        string
	DisplayName  string
	Email        sql.NullString
	PasswordHash sql.NullString
	PinHash      sql.NullString
	CustomerID   sql.NullInt64
	CreatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Realm,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.PinHash,
		arg.CustomerID,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Realm,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.CustomerID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getDriverByName = `-- name: GetDriverByName :one
SELECT id, realm, display_name, email, password_hash, pin_hash, customer_id, active, created_at FROM users WHERE display_name = ? AND realm = 'driver'
`

func (q *Queries) GetDriverByName(ctx context.Context, displayName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getDriverByName, displayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Realm,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.CustomerID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.user_id, s.realm, s.expires_at, u.display_name, u.active
FROM sessions s JOIN users u ON u.id = s.user_id WHERE s.id = ?
`

type GetSessionRow struct {
	ID          string
	UserID      int64
	Realm       string
	ExpiresAt   time.Time
	DisplayName string
	Active      bool
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Realm,
		&i.ExpiresAt,
		&i.DisplayName,
		&i.Active,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, realm, display_name, email, password_hash, pin_hash, customer_id, active, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Realm,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.CustomerID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, realm, display_name, email, password_hash, pin_hash, customer_id, active, created_at FROM users WHERE email = ? AND realm = 'office'
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Realm,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.PinHash,
		&i.CustomerID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listUsersByRealm = `-- name: ListUsersByRealm :many
SELECT id, realm, display_name, email, password_hash, pin_hash, customer_id, active, created_at FROM users WHERE realm = ? AND active = TRUE ORDER BY display_name
`

func (q *Queries) ListUsersByRealm(ctx context.Context, realm string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByRealm, realm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Realm,
			&i.DisplayName,
			&i.Email,
			&i.PasswordHash,
			&i.PinHash,
			&i.CustomerID,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET active = ? WHERE id = ?
`

type SetUserActiveParams struct {
	Active bool
	ID     int64
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, setUserActive, arg.Active, arg.ID)
	return err
}

const setUserPinHash = `-- name: SetUserPinHash :exec
UPDATE users SET pin_hash = ? WHERE id = ?
`

type SetUserPinHashParams struct {
	PinHash sql.NullString
	ID      int64
}

func (q *Queries) SetUserPinHash(ctx context.Context, arg SetUserPinHashParams) error {
	_, err := q.db.ExecContext(ctx, setUserPinHash, arg.PinHash, arg.ID)
	return err
}
